steps:
- name: 'python:3.12' # Choose your desired Python version
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt', '-t', '.']

- name: 'googlecloudplatform/buildpacks/python:3.12'
  args: ['deploy', '--service=ai-email-bot', '--region=asia-south1', '--source=.'] # Replace placeholders

options:
  logging: CLOUD_LOGGING_ONLY # For better log integration with GCP
